---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux
environment:
  GOOS: linux
  GOARCH: amd64

steps:
  - name: get
    image: golang:1.14.0
    commands:
      - go mod download

  - name: linelint
    group: test
    image: fernandrone/linelint:latest
    pull: true

  - name: golangci-lint
    group: test
    image: golangci/golangci-lint:v1.26.0
    commands:
      - golangci-lint run

  - name: test
    group: test
    image: golang:1.14.0
    commands:
      - go test ./...

  - name: build
    image: golang:1.14.0
    commands:
      - go build -o bin/linelint

  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      dockerfile: .build/Dockerfile
      repo: fernandrone/linelint
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - push
    - tag

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux
environment:
  GOARCH: arm64
  GOOS: linux

steps:
  - name: get
    image: golang:1.14.0
    commands:
      - go mod download
  - name: test
    image: golang:1.14.0
    commands:
      - go test ./...

  - name: build
    image: golang:1.14.0
    commands:
      - go build -o bin/linelint

  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      auto_tag_suffix: arm64
      dockerfile: .build/Dockerfile
      repo: fernandrone/linelint
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - push
    - tag

depends_on:
  - linux-amd64
